# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Mediplus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for Mediplus
  pod 'Firebase/Core'
  pod 'FirebaseCore'
  pod 'Firebase/Storage', '~> 5.3.0'
  pod 'Firebase/Database', '~> 5.3.0'


end

